apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: yklee2002/order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: STOCK_SERVICE_URL
              value: http://stockconfirm-service
            - name: PAYMENT_SERVICE_URL
              value: http://payment-service
            - name: DELIVERY_SERVICE_URL
              value: http://delivery-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30110
