spring.application.name=order
services.stock.url=${STOCK_SERVICE_URL:http://stockconfirm-service}
services.payment.url=${PAYMENT_SERVICE_URL:http://payment-service}
services.delivery.url=${DELIVERY_SERVICE_URL:http://delivery-service}
services.book.url=${BOOK_SERVICE_URL:http://resttemplateserver:8080}
